### ISSUE TITLE
 Black screen on non-English system DotOs 5.2 Redmi5a

### ISSUE THREAD

**Issue by WERDHA** [DotOS/issues#90]
## Build date

```
dotOS-R-v5.2-rolex-OFFICIAL-20210915.zip 
```

## Expected Behavior

```

```

## Current Behavior

```
I kind of found a problem with a black screen: if I did not change the language from English, everything worked fine as soon as I put Russian (because i'm russian) or another language and pressed the volume rocker - then black screen. It is on vanilla and gapps version too. It is not in me, many users have this problem, after system is always black (not usable)
```

## Possible Solution

```
Edit here
```

## Steps to Reproduce

```
1.
2.
3.
4.
```

/device Redmi 4A/5a (rolex)
/version dot 5.2
/variant vanilla AND gapps

**Comment by Ctapchuk** [comment]
The same problem with Russian lang for another unofficial device.
It seems the problem is here: https://github.com/DotOS/android_frameworks_base/blob/ed3abc369af8400ffd0d669c0b2e0a7e709958e5/packages/SystemUI/res/values-ru/strings.xml#L642
log:
```
--------- beginning of crash
09-16 20:43:38.505  3969  3969 E AndroidRuntime: FATAL EXCEPTION: main
09-16 20:43:38.505  3969  3969 E AndroidRuntime: Process: com.android.systemui, PID: 3969
09-16 20:43:38.505  3969  3969 E AndroidRuntime: java.lang.NumberFormatException: For input string: "40 "
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:615)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:650)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.systemui.volume.VolumeDialogImpl.updateVolumeRowSliderH(VolumeDialogImpl.java:1515)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.systemui.volume.VolumeDialogImpl.updateVolumeRowH(VolumeDialogImpl.java:1442)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.systemui.volume.VolumeDialogImpl.onStateChangedH(VolumeDialogImpl.java:1308)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.systemui.volume.VolumeDialogImpl$5.onStateChanged(VolumeDialogImpl.java:1623)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.systemui.volume.VolumeDialogControllerImpl$C$3.run(VolumeDialogControllerImpl.java:885)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7666)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
full logcat: [logcat (2).txt](https://github.com/DotOS/issues/files/7184061/logcat.2.txt)

**Comment by WERDHA** [comment]
Sorry, i'm a noob, dont know how make logs and  what to do with them. Hope for developers to fix

**Comment by Pushkin31** [comment]
> The same problem with Russian lang for another unofficial device.
> It seems the problem is here: [DotOS/android_frameworks_base@`ed3abc3`/packages/SystemUI/res/values-ru/strings.xml#L642](https://github.com/DotOS/android_frameworks_base/blob/ed3abc369af8400ffd0d669c0b2e0a7e709958e5/packages/SystemUI/res/values-ru/strings.xml#L642)
> log:
> 
> ```
> --------- beginning of crash
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: FATAL EXCEPTION: main
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: Process: com.android.systemui, PID: 3969
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: java.lang.NumberFormatException: For input string: "40 "
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:615)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at java.lang.Integer.parseInt(Integer.java:650)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.systemui.volume.VolumeDialogImpl.updateVolumeRowSliderH(VolumeDialogImpl.java:1515)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.systemui.volume.VolumeDialogImpl.updateVolumeRowH(VolumeDialogImpl.java:1442)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.systemui.volume.VolumeDialogImpl.onStateChangedH(VolumeDialogImpl.java:1308)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.systemui.volume.VolumeDialogImpl$5.onStateChanged(VolumeDialogImpl.java:1623)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.systemui.volume.VolumeDialogControllerImpl$C$3.run(VolumeDialogControllerImpl.java:885)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7666)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
> 09-16 20:43:38.505  3969  3969 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> ```
> 
> full logcat: [logcat (2).txt](https://github.com/DotOS/issues/files/7184061/logcat.2.txt)

I join to the problem of Ctapchuk. I have the same device as he has - realme 6 pro, and I also experience this bug...
